// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cofire.proto

/*
Package cofire is a generated protocol buffer package.

It is generated from these files:
	cofire.proto

It has these top-level messages:
	Features
	Entry
	Rating
	Message
	Update
*/
package cofire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Stage are the internal stages of the cofire learner.
type Stage int32

const (
	Stage_ENTRY   Stage = 0
	Stage_PRODUCT Stage = 1
	Stage_USER    Stage = 2
)

var Stage_name = map[int32]string{
	0: "ENTRY",
	1: "PRODUCT",
	2: "USER",
}
var Stage_value = map[string]int32{
	"ENTRY":   0,
	"PRODUCT": 1,
	"USER":    2,
}

func (x Stage) String() string {
	return proto.EnumName(Stage_name, int32(x))
}
func (Stage) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Features are the factors and a bias for a user or product.
type Features struct {
	V    []float64 `protobuf:"fixed64,1,rep,packed,name=v" json:"v,omitempty"`
	Bias float64   `protobuf:"fixed64,2,opt,name=bias" json:"bias,omitempty"`
}

func (m *Features) Reset()                    { *m = Features{} }
func (m *Features) String() string            { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()               {}
func (*Features) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Features) GetV() []float64 {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *Features) GetBias() float64 {
	if m != nil {
		return m.Bias
	}
	return 0
}

// Entry are the factors (either U or P) for a user or product.
type Entry struct {
	U *Features `protobuf:"bytes,1,opt,name=u" json:"u,omitempty"`
	P *Features `protobuf:"bytes,2,opt,name=p" json:"p,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entry) GetU() *Features {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *Entry) GetP() *Features {
	if m != nil {
		return m.P
	}
	return nil
}

// Rating represents the score that a user gives to a product.
// Cofire Learner accepts Rating messages to factorize the rating matrix.
type Rating struct {
	UserId    string  `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ProductId string  `protobuf:"bytes,2,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Score     float64 `protobuf:"fixed64,3,opt,name=score" json:"score,omitempty"`
}

func (m *Rating) Reset()                    { *m = Rating{} }
func (m *Rating) String() string            { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()               {}
func (*Rating) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rating) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Rating) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Rating) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

// Message are internal messages of the Cofire Learner.
type Message struct {
	Stage  Stage     `protobuf:"varint,1,opt,name=stage,enum=cofire.Stage" json:"stage,omitempty"`
	Rating *Rating   `protobuf:"bytes,2,opt,name=rating" json:"rating,omitempty"`
	F      *Features `protobuf:"bytes,3,opt,name=f" json:"f,omitempty"`
	Iters  uint32    `protobuf:"varint,4,opt,name=iters" json:"iters,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Message) GetStage() Stage {
	if m != nil {
		return m.Stage
	}
	return Stage_ENTRY
}

func (m *Message) GetRating() *Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func (m *Message) GetF() *Features {
	if m != nil {
		return m.F
	}
	return nil
}

func (m *Message) GetIters() uint32 {
	if m != nil {
		return m.Iters
	}
	return 0
}

// Update messages overwrite the U or P features of in the user/product's
// entry.
type Update struct {
	U *Features `protobuf:"bytes,2,opt,name=u" json:"u,omitempty"`
	P *Features `protobuf:"bytes,3,opt,name=p" json:"p,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Update) GetU() *Features {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *Update) GetP() *Features {
	if m != nil {
		return m.P
	}
	return nil
}

func init() {
	proto.RegisterType((*Features)(nil), "cofire.Features")
	proto.RegisterType((*Entry)(nil), "cofire.Entry")
	proto.RegisterType((*Rating)(nil), "cofire.Rating")
	proto.RegisterType((*Message)(nil), "cofire.Message")
	proto.RegisterType((*Update)(nil), "cofire.Update")
	proto.RegisterEnum("cofire.Stage", Stage_name, Stage_value)
}

func init() { proto.RegisterFile("cofire.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x9d, 0x6d, 0x77, 0xdb, 0x4e, 0xff, 0xb0, 0x0c, 0x82, 0x7b, 0x51, 0x96, 0x15, 0x64,
	0x15, 0xe9, 0xa1, 0x3e, 0x82, 0x56, 0xed, 0xc1, 0x3f, 0xa4, 0xad, 0xe0, 0x49, 0xd2, 0x6e, 0x5a,
	0xf6, 0xd2, 0x0d, 0x49, 0xb6, 0xe0, 0x3b, 0xf8, 0xd0, 0x92, 0x64, 0x7b, 0xab, 0x78, 0xcb, 0x37,
	0x5f, 0xf2, 0xe5, 0x37, 0x33, 0x38, 0x58, 0x57, 0x9b, 0x52, 0x89, 0xb1, 0x54, 0x95, 0xa9, 0x28,
	0xf2, 0x2a, 0xbb, 0xc5, 0xee, 0xa3, 0xe0, 0xa6, 0x56, 0x42, 0xd3, 0x00, 0x61, 0x9f, 0x40, 0xda,
	0xca, 0x81, 0xc1, 0x9e, 0x08, 0xdb, 0xab, 0x92, 0xeb, 0x24, 0x48, 0x21, 0x07, 0xe6, 0xce, 0xd9,
	0x13, 0x86, 0xd3, 0x9d, 0x51, 0xdf, 0x74, 0x81, 0x50, 0x27, 0x90, 0x42, 0xde, 0x9f, 0xc4, 0xe3,
	0x26, 0xf8, 0x90, 0xc3, 0xa0, 0xb6, 0xbe, 0x74, 0x2f, 0x8f, 0xfa, 0x32, 0xfb, 0xc0, 0x88, 0x71,
	0x53, 0xee, 0xb6, 0x74, 0x86, 0x9d, 0x5a, 0x0b, 0xf5, 0x55, 0x16, 0x2e, 0xaf, 0xc7, 0x22, 0x2b,
	0x67, 0x05, 0x9d, 0x23, 0x4a, 0x55, 0x15, 0xf5, 0xda, 0x58, 0x2f, 0x70, 0x5e, 0xaf, 0xa9, 0xcc,
	0x0a, 0x3a, 0xc5, 0x50, 0xaf, 0x2b, 0x25, 0x92, 0x96, 0xe3, 0xf3, 0x22, 0xfb, 0x01, 0xec, 0xbc,
	0x08, 0xad, 0xf9, 0x56, 0xd0, 0x25, 0x86, 0xda, 0xf0, 0xad, 0x70, 0xb9, 0xa3, 0xc9, 0xf0, 0xc0,
	0x31, 0xb7, 0x45, 0xe6, 0x3d, 0xba, 0xc2, 0x48, 0x39, 0x90, 0x86, 0x76, 0x74, 0xb8, 0xe5, 0xf1,
	0x58, 0xe3, 0xda, 0x86, 0x36, 0xee, 0xab, 0xa3, 0x0d, 0x6d, 0x2c, 0x4e, 0x69, 0x84, 0xd2, 0x49,
	0x3b, 0x85, 0x7c, 0xc8, 0xbc, 0xc8, 0x9e, 0x31, 0x5a, 0xca, 0x82, 0x1b, 0xe1, 0x07, 0x16, 0xfc,
	0x33, 0xb0, 0x3f, 0xf3, 0xe5, 0xcd, 0x35, 0x86, 0x8e, 0x9b, 0x7a, 0x18, 0x4e, 0x5f, 0x17, 0xec,
	0x33, 0x3e, 0xa1, 0x3e, 0x76, 0xde, 0xd9, 0xdb, 0xc3, 0xf2, 0x7e, 0x11, 0x03, 0x75, 0xb1, 0xbd,
	0x9c, 0x4f, 0x59, 0x1c, 0xac, 0x22, 0xb7, 0xe1, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba,
	0x42, 0xbf, 0xde, 0xf1, 0x01, 0x00, 0x00,
}
